[build]
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
releaseCommand = "python manage.py migrate"
startCommand = "gunicorn botanica.wsgi:application --bind 0.0.0.0:$PORT"