# Generated by Django 4.2.29 on 2026-03-26 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=300, unique=True)),
                ('common_names', models.CharField(help_text='Comma-separated common names', max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('kingdom', models.CharField(default='Plantae', max_length=100)),
                ('order', models.CharField(blank=True, max_length=100)),
                ('genus', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(help_text='General description and significance')),
                ('morphology', models.TextField(blank=True, help_text='Physical description: leaves, stems, flowers, roots')),
                ('habitat', models.TextField(blank=True, help_text='Where it grows, soil, climate, altitude')),
                ('distribution', models.TextField(blank=True, help_text='Geographic range')),
                ('bloom_season', models.CharField(blank=True, max_length=200)),
                ('edibility', models.CharField(choices=[('edible', 'Edible'), ('medicinal', 'Medicinal'), ('toxic', 'Toxic'), ('caution', 'Use with Caution'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('uses_medicinal', models.TextField(blank=True, help_text='Medicinal uses and traditional applications')),
                ('uses_culinary', models.TextField(blank=True, help_text='Culinary and edible uses')),
                ('uses_other', models.TextField(blank=True, help_text='Dye, craft, ecological, spiritual, etc.')),
                ('preparation_methods', models.TextField(blank=True, help_text='How to prepare: teas, tinctures, poultices, etc.')),
                ('warnings', models.TextField(blank=True, help_text='Toxicity, contraindications, look-alikes')),
                ('field_notes', models.TextField(blank=True, help_text='Personal observations in the field')),
                ('locations_observed', models.TextField(blank=True, help_text='Where you have personally seen this plant')),
                ('seasonal_patterns', models.TextField(blank=True, help_text='When it appears, peaks, and fades')),
                ('symbolism', models.TextField(blank=True, help_text='Cultural and historical symbolism')),
                ('energetic_qualities', models.TextField(blank=True, help_text='Traditional energetic or elemental associations')),
                ('personal_reflections', models.TextField(blank=True, help_text='Your personal relationship with this plant')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='grimoire/plants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Lamiaceae', max_length=200)),
                ('common_name', models.CharField(blank=True, help_text='e.g. Mint family', max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('use', 'Use'), ('habitat', 'Habitat'), ('quality', 'Quality'), ('season', 'Season')], default='use', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Properties',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='grimoire/gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='grimoire.plant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='grimoire.plantfamily'),
        ),
        migrations.AddField(
            model_name='plant',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='plants', to='grimoire.plantproperty'),
        ),
        migrations.AddField(
            model_name='plant',
            name='related_plants',
            field=models.ManyToManyField(blank=True, to='grimoire.plant'),
        ),
        migrations.CreateModel(
            name='ObservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=300)),
                ('coordinates', models.CharField(blank=True, help_text='lat,lon e.g. -1.2921,36.8219', max_length=100)),
                ('notes', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='grimoire/observations/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='grimoire.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
